### PR TITLE
Feat/security honeypot helpers

### PR DESCRIPTION
**Pull request by jamiemonksuk**
Honeypot field name can optionally be overridden
by a config honeypot.field_name if desired

### CODE REVIEW

**Comment by aitken85** [comment]
`Security::honeypotSet()` Should probably use a return statement instead of directly echoing to match almost all our other sprout3 helpers. Other than that, all good.

**Comment by aitken85** [comment]
@gwillz Happy to go ahead to merge this?

**Comment by gwillz** [comment]
Yeah I reckon so, it's tried and tested.

If I were being pedantic, I don't enjoy that `honeypotCheckOrDie()` doesn't actually die - it throws. 

To be clear I don't like `die()` either (I wish it would die) and I prefer exceptions any day. It's only the name is quite misleading.

**Comment by gwillz** [comment]
Actually, the prefixing honeypot really screams that this should be in a Honeypot helper.

**Comment by gwillz** [comment]
OK so this is all in a new helper, also added a twig helper. Everyone happy?

**Comment by jamiemonksuk** [comment]
I like the don't tell anyone commit

**Review by aitken85 — APPROVED** [review]

**Pull request merged**
