### PR TITLE
Field element helper: Total selector field

### PR DESCRIPTION
**Pull request by LukeKB**
Used this in-house a few times now so thought it should be added to Fb. Pls review code.
Wrote the totalSelector jQuery plugin myself

Working in both admin and front-end
/dbtools/testSkinTemplatesAction/default/inner
/admin/style_guide/forms

### CODE REVIEW

**Comment by TheJosh** [comment]
Is there a way this can work *without* adding a method to the `Form` class? I mean calling code is generally able to call any given method "bare" (i.e. without the error code, label, etc) by calling `Fb` directly, but this looks like it would only work via the form class, which breaks this idea

**Comment by TheJosh** [comment]
Also, passing an array of stuff via `$attributes` is evil; this is what the `$options` array was designed for - all the non-attribute stuff which a field might need.

**Comment by LukeKB** [comment]
Dear @TheJosh,

Your face is rubbish. See changes in commit [5ab1bee](https://github.com/Karmabunny/sprout3/pull/35/commits/5ab1bee5c9bbd9321c254315d158a72b3d5dd3dc)

Altered my plugin to work with the markup of `Form::fieldPlain()` and removed modifications to `Form` class.

Sub-fields are now set through $options instead of $attributes. Still using a sub-array - how else should it be done?

**Comment by TheJosh** [comment]
Thanks. That's a ton better. `$options` nested array is fine - the problem was nested arrays in `$attributes`.

**Pull request merged**
